### ISSUE TITLE
Content: Weekly Navigator Checks/Content Maintenance

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#1029]
[X] make the link to the Treasury M/WBE more obvious - website
[X ] Update NJ Reg task with information on BRC - @CeciliaRam 
[X] Create contextual information for "form and register" my business @CeciliaRam 
[X] Should we consider changes to the Pharmacy Task Screen to make it more clear that there is an inspection -- reviewed with Don, need to tell team.
[X] Obtain Site Safety Permits- cosmo needs updated dependencies

**Comment by Jesslax** [comment]
@kmelefsky not done yet! Reopening.

**Comment by CeciliaRam** [comment]
BRC contextual info: https://github.com/newjersey/navigator.business.nj.gov/blob/main/content/src/display-content/contextual-information/business-reg-certificate.md

Form and Register Business contextual info: https://github.com/newjersey/navigator.business.nj.gov/blob/main/content/src/display-content/contextual-information/form-and-register-business.md

Register for State Taxes task (step 3) has been edited to show "Business Registration Certificate (BRC)" instead of Proof of Filing

**Comment by Jesslax** [comment]
@CeciliaRam I believe you are done with your two tasks on this tkt, right?

**Comment by CeciliaRam** [comment]
@Jesslax yes, the 2 tasks assigned to me are done. Task: "Review copy of Oscar onboarding" is keeping this ticket open
