### ISSUE TITLE
As Jessica, I want to be able to archive files that are no longer in use

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1064]
As Jessica, I want to be able to archive files that are no longer in use. I need an archive folder so I can reference the files in the future if I need to. I need an archive folder in the following folders:
- contextual information
- tasks

These archives folders need to be separate so I know if the archived file is contextual info or a task.

**Comment by aloverso** [comment]
@Jesslax 

Folders have been created:
- `archived-contextual-info` folder: https://github.com/newjersey/navigator.business.nj.gov/tree/1064-archive-folders/content/src/display-content/archived-contextual-info
- `archived-tasks` folder: https://github.com/newjersey/navigator.business.nj.gov/tree/1064-archive-folders/content/src/roadmaps/archived-tasks

Here's the process for moving a file within the GitHub editor:

1. Go to the file you want to move, and click edit (as usual)

2. You will be editing the line with the **file name** - for this example I will move "alternate-name" to the new folder
<img width="852" alt="Screen Shot 2021-11-30 at 10 33 58 AM" src="https://user-images.githubusercontent.com/6563663/144078676-0fcca843-f4d3-4f8b-b314-41ed78ee1d9e.png">

3. Type `../` (2 periods followed by a slash) to the front of the filename
![image](https://user-images.githubusercontent.com/6563663/144078949-f39a3bd0-3b03-4670-961e-f0cc52dbb967.png)

At the point at which you type the slash, GitHub will interpret this as meaning "one folder level up from where we are right now" and change the path, removing what you typed in the process. This is the _correct_ outcome.

![image](https://user-images.githubusercontent.com/6563663/144079193-df5f54df-252c-4904-a857-67536f94d9e9.png)

Note how the file is now listed as within the `/roadmaps` folder, instead of `/roadmaps/tasks` like it was previously.

4. Now, at the front of the filename, start typing the new folder you want it in, followed by a slash. In this case `archived-tasks/`. Similar to when we typed the dots, as soon as you type the slash, it will interpret the text as a folder path and adjust the path appropriately:

![image](https://user-images.githubusercontent.com/6563663/144079706-d666a2ea-2e00-4b45-b6af-6831123320d3.png)

![image](https://user-images.githubusercontent.com/6563663/144079782-c035685b-089c-4bd5-b68e-06a87ad7732e.png)

When the final path looks correct like this, showing that it is in `src / roadmaps / archived-tasks / taskname.md` then you can commit and do the usual process.

The process is exactly the same for contextual info. You type `../` to move one-level up in the folder hierarchy, and then type the new folder name followed by slash, which for that will be `archived-contextual-info`

Let me know if you have questions!

**Comment by Jesslax** [comment]
@aloverso I am getting a 404 for both of those first two links. I am trying this out now.

**Comment by aloverso** [comment]
@Jesslax oops my bad! I fixed the links

**Comment by aaronvux** [comment]
Moving to staging.
