### ISSUE TITLE
Add Visual Stepper to Business Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1419]
As Poppy, I need a visual representation of the steps I need to complete on the Business Formation pages so I know how much I have left to complete and where I currently am.

## Acceptance criteria
- Add Visual Stepper to Business Formation
-- Business
-- Contacts
-- Review
-- Billing
- After each step is complete, display the checkmark icon in the stepper and update the color of the line to blue
- The screenreader will read the step the user is on as they move through the page.
-- Business - Step 1 of 4
-- Contacts - Step 2 of 4
-- Review - Step 3 of 4
-- Billing - Step 4 of 4 

## Design
Desktop:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6693%3A148227

Mobile:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7156%3A192250

## Additional Acceptance Criteria:
- Follows Design
- Works in Mobile
- 508 Compliance

## Notes
- [x] PO Approval
- [x] UX Review

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by FarazA22** [comment]
@fiorella-io @aaronvux keeping all completed steps blue with a checkmark will cause confusion. On Tablet+, the user can no longer tell which step they are one if the are on a previously completed tab. For mobile, we are requiring the user to do additional mental work to figure out the where they are because the boxes will keep the completed state, but the label will change.

**Comment by FarazA22** [comment]
@aaronvux removed step number from mobile

**Comment by aaronvux** [comment]
@FarazA22 we don't have to always show the blue checkbox when the user goes back.  We'll update the functionality as apart of the clickable stepper story.  Moving this one to done.  Looks good!
