### ISSUE TITLE
Add Visual Formatting Options to Task Screens

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1470]
As a Navigator user, I need the ability to easily consume information on tasks screens so that I am not overwhelmed by large blocks of text.

## Acceptance Criteria
- Update all tasks screens to be capable of the implementing following formats:

**Format Update**
- Horizontal Rule
- Sub Header
- Green Box
  - Sub-header
  - Bullets

## Design

**Desktop**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200323

**Mobile**
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200629

## Additional Acceptance Criteria
- Follows Design
- Works in Mobile
- 508 Compliant

## Notes

- [x] UX Review
- [x] PO Approval
- [x] Content Review

**Comment by aaronvux** [comment]
@carye3 is there a mobile design for this?

**Comment by carye3** [comment]
@aaronvux https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8592%3A197374

**Comment by carye3** [comment]
Figma files finalized @FarazA22 @namanaman

**Comment by aloverso** [comment]
@aaronvux @carye3 what is meant by subheader? which part of the design is an example of that?

**Comment by aaronvux** [comment]
@aloverso
"What you'll get" is the subheader

<img width="646" alt="Screen Shot 2022-02-04 at 3 29 45 PM" src="https://user-images.githubusercontent.com/36163601/152598892-a68587bc-cab2-4ae5-99de-ffefc2d73eea.png">

**Comment by aloverso** [comment]
Got it, so subheader in green box

**Comment by aloverso** [comment]
@aaronvux ready for review. no content yet in the site though because @Jesslax is still finalizing where we want to start adding these elements

Here's how it works:

## Horizontal line

Can be added by inserting three dashes `---` on any line

For example, this will insert a line between paragraphs 1 and 2

```
paragraph 1

---

paragraph 2
```

## subheadings

Can be added by prefixing any line with hash marks 

We don't use first-level headers within text because that will conflict with the page title

`##` is a second-level header (font size 22px and bold)
`###` is a third-level header (font size 16px and bold)

**NOTE** it's important for accessibility that we use cascading header levels - ie, we can't skip directly to a third-level header, third-levels should ALWAYS exist within a 2nd-level header. 

example:

```
## a subheader

a paragraph

### a sub-subheader

a paragraph

### another sub-sub-header

a paragraph
```

Also, note there should be a space between the hashes and the text: it should be `## header` NOT `##header`

## green box

Any text can be enclosed in the green boxes by prefixing the line with `> `

Much like the headers, ensure there is a space after the `>` and before the rest of the text

You can use any other style elements with this as if it were normal text: bullet points, links, headers, horizontal lines, etc.

For example: 
```
some text

> this is now within a green box
> ## subheader in a green box
> paragraph in the box
> - bullet item 1
> - bullet item 2

this is now outside the green box

> this is in a new, different green box
```
