### ISSUE TITLE
Design QA: B.NJ Redesign

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1477]
QA biz.nj pages before publishing

### Priority
- [x] Search page: 
  - [x] 308px max width of sidebar
- [x] Sign Up for Newsletter header should be consistent with other sidebar headers (H3)
- [ ] Design: discuss what features to A/B test via Google Optimize
- [x] Measure: are accordions helping users? UPDATE 7.29: most users prefer no accordions, though they pass usability
  - [x] Joe to establish baseline click rate of sub-page CTAs, and then try out accordions and see if they negatively impact those click rates. Follow-up:
    - [x] Experiment with content section at top; if that doesn't work:
    - [x] Experiment with multi-level navigation
  - [x] Design to conduct unmoderated usability testing around usefulness / usability of accordions
  - [ ] 7.29: Consider adding table of contents where appropriate, remove accordions
- [ ] Ask Mike if automated testing (via Cypress) is possible for B.NJ
- [x] Updates: Check spanish
  - [x] Sidebar nav not translating <img width="400" alt="image" src="https://user-images.githubusercontent.com/62653834/161602821-39737f64-67d7-4d27-8f6b-a15bd67cd770.png">
  - [ ] Sort by not translating <img width="304" alt="image" src="https://user-images.githubusercontent.com/62653834/161602881-81976156-e60a-4712-b92a-d26364198b9e.png">
    - [ ] A - Z, Z - A 
  - [x] Banner not translating <img width="1075" alt="image" src="https://user-images.githubusercontent.com/62653834/161602928-4141d04e-6578-492b-bb2e-6361948c7b2f.png">
  - [x] iFrame Issue in Spanish: subscribe <img width="394" alt="image" src="https://user-images.githubusercontent.com/62653834/166292622-ec06408b-5774-4690-ba3e-78eda8667bca.png">
  - [x] iFrame Issuein Spanish: Intercom <img width="689" alt="image" src="https://user-images.githubusercontent.com/62653834/166292576-7eafba12-abca-42d7-8106-abaa8baef742.png">
- [x] Make the reset button consistent to match the Updates page
<img width="324" alt="image" src="https://user-images.githubusercontent.com/91498500/165395041-3d49516a-f0a4-4ccf-9801-8d1b5946027e.png"> <img width="293" alt="image" src="https://user-images.githubusercontent.com/91498500/165394821-86b6672c-61a4-4c20-94b4-a2a135a6bea7.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/91498500/165394862-67ee4517-16d0-4b9b-be65-801b4e79f6c6.png">

- [ ] breadcrumbs not wrapping when translated into Spanish (mobile)
<img width="338" alt="image" src="https://user-images.githubusercontent.com/91498500/165393971-e93a7a08-c3a7-445f-9ada-e35e2252d3ec.png">
  
- [x] content translated into Spanish renders in all caps
<img width="287" alt="image" src="https://user-images.githubusercontent.com/91498500/165394318-4390f7dc-af64-4ba3-b420-7a44a8c3168c.png">
   
- [x] Not all tags translating <img width="335" alt="image" src="https://user-images.githubusercontent.com/62653834/161603099-7960c893-b22b-41ee-843e-06a977d2b799.png">
- [x] Updates (Dsk)
  - [x] Any links to another site should open a new tab
  - [x] "Read More" should only be used for seeing more content on the site.  "Learn More" should be used with a link out icon for any external links
  - [x] Search: "Find Updates"
  - [x] Nav bar is too transparent
  - [x] Reduce spacing between tiles to 16 total px
  - [x] Paragraph break within tiles (ie between Eligibility and Benefits)
  - [x] Tile body text: 16px, 24px line height
- [x] Newsletter Sidebar:
  - [x] Success message: eg "Success! Check your inbox for a confirmation email.", in green 
- [ ] Updates (Dsk) - Spanish
- [x] Updates (Mbl)
  - [x] Newsletter signup below breadcrumb and gray line
  - [x] Result counter: reduce to 16px, fix issue where it shows 0 items 
  - [x] Paragraph break within tiles (ie between Eligibility and Benefits)
- [ ] Updates (Mbl) - Spanish
- [x] Updates Sub-Page (Dsk)
  - [x] Highlight "All Updates" in sidebar nav if nothing is hightlighted otherwise
- [ ] Updates Sub-Page (Mbl)
- [x] Hamburger menu: accordions for all topics
- [ ] Chat in Mobile issue -- @dltinnovate **2.15.22 - chatting with Bablic rep**
- [x] #1535
- [x] Back to top button on Funding and Updates sections
- [x] "Back to Topics" to "All Topics"
- [x] Funding Page
  - [x] Search "Find Opportunities"
- [x] Low res icons <img width="405" alt="image (18)" src="https://user-images.githubusercontent.com/62653834/160872360-df36333f-2131-4e91-8e8f-f1f1ba7f05e7.png">
- [x] Padding between homepage PSOG tiles <img width="651" alt="image (19)" src="https://user-images.githubusercontent.com/62653834/160872323-a6e1d7b6-ef96-4d79-8310-dd388e180c21.png">

### Other
- [x] Hamburger Menus - Reduced Width (Mbl)
- [x] Hamburger Menus  - Reduced Width (Mbl) - Spanish
- [x] Homepage (Dsk)
- [x] Homepage (Mbl)
- [x] Homepage (Dsk) - Spanish
- [x] Homepage (Mbl) - Spanish
- [x] Topic Sub-Page (Desktop)
- [x] Topic Sub-Page (Mobile)
  - [x] Sticky Side-Nav @dltinnovate 2.15.22
    - Not sticky for Funding & Updates pages since you'd be unable to scroll all filter options
  - [x] Mobile Sidebar nav
- [x] Topics Landing (Dsk)
- [x] Topics Landing (Dsk) - Spanish
- [x] Topics Landing (Mbl)
- [x] Topics Landing (Mbl) - Spanish
- [x] Funding (Dsk)
- [x] Funding (Dsk) - Spanish
- [x] Funding (Mbl)
- [x] Funding (Mbl) - Spanish
- [x] Hamburger Menu New Design (Mbl)
- [x] Hamburger Menus New Design (Mbl) - Spanish
- [x] Funding (Dsk & Mobile, Eng & Spanish): dropdown multi-select for filter options (in order to avoid long-scroll through filter options to reach results in mobile)
- [x] Funding (Dsk & Mbl, Eng & Spanish): remove "Filtering by" text when there's nothing selected
- [x] New Sub Pages

## Files
[Figma](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73595)

### Sprint 28
**Design Tasks**
- [ ] Upload hover states for all buttons
- [x] PNG of nj logo?
- [ ] [New Sub-Page](https://beta.business.nj.gov/covid/health-care-facilities-vaccine-requirements) breadcrumb and sidebar nav
- [ ] New Design for [Licenses & Certs page](https://beta.business.nj.gov/licensing-and-certification-guide) 
- [ ] New Plan Icon @fiorella-io @carye3 
![image](https://user-images.githubusercontent.com/62653834/151602913-593be4e8-093c-4dbc-93c8-a9a67c8a0439.png)

**Delivery Tasks**
- [ ] #1473
  - [ ] Reach out to Intercom to increase bottom margin for text entry field
  - [ ] Move the Bablic language tab when viewing intercom @dltinnovate discuss with @mikewolfd 
  - [ ] Move the text field up
- [ ] #1476
  - [ ] Decrease Opacity
  - [ ] Reduce width of menu to show page on left
  - [ ] Talk to mike about other solutions

## Old Tasks
# Old Tasks
**General**
- [ ] 1.5px line weight (except sidenav) for all dividers
- [ ] Replace back to top button with thicker line weight version

**Nav Bar**
- [ ] Match padding of buttons with divider
- [ ] Replace NJ logo with png
- [ ] Change divider to grey A9AEB1
- [ ] Text weight: 500
- [ ] Dropdown menus: 24px padding on bottom and top
- [ ] Search: when typing, change text color to body text color (1B1B1B)

**Banner**
- [ ] Reduce background illustration to 15%
- [ ] Replace PNG icon with SVG 
- [ ] Description text: 20px, 350 weight
- [ ] Vertical padding 50px

**Side Nav**
- [ ] Stick to top left of screen (desktop) once you scroll beyond the fold

**Body**
- [ ] Body text weight: 300
- [ ] Header 2: remove 20px padding

**Comment by dltinnovate** [comment]
-Priority
- [ ]  Updates: Check spanish
**Updates (Dsk)**
   - [ ] Any links to another site should open a new tab
   - [ ] "Read More" should only be used for seeing more content on the site. "Learn More" should be used with a link out icon for any external links
   - [ ] Search: "Find Updates"
   - [ ] Nav bar is too transparent
   - [ ]  Reduce spacing between tiles to 16 total px
   - [ ]  Paragraph break within tiles (ie between Eligibility and Benefits)
   - [ ] Tile body text: 16px, 24px line height

 **Newsletter Sidebar:**
- [ ] Success message: eg "Success! Check your inbox for a confirmation email.", in green

Updates (Dsk) - Spanish
**Updates (Mbl)**
- [ ] Newsletter signup below breadcrumb and gray line
- [ ]  Result counter: reduce to 16px, fix issue where it shows 0 items
- [ ] Paragraph break within tiles (ie between Eligibility and Benefits)
- [ ] Updates (Mbl) - Spanish
- [ ] Updates Sub-Page (Dsk)
- [ ] Highlight "All Updates" in sidebar nav if nothing is hightlighted otherwise 
- [ ] Updates Sub-Page (Mbl)
- [ ] Hamburger menu: accordions for all topics
- [ ] Chat in Mobile issue -- @dltinnovate 2.15.22 - chatting with Bablic rep
 https://github.com/newjersey/navigator.business.nj.gov/issues/1535
 
**General**
- [ ] Back to top button on Funding and Updates sections
- [ ] "Back to Topics" to "All Topics"

 Funding Page
- [ ] Search "Find Opportunities"

**Comment by carye3** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/62653834/166292576-7eafba12-abca-42d7-8106-abaa8baef742.png">

**Comment by carye3** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/62653834/166292622-ec06408b-5774-4690-ba3e-78eda8667bca.png">

**Comment by amandabeall** [comment]
@dltinnovate I found two small bugs in the Plan section. See below and let me know if you have any questions

1. Plan > Buy an Existing Business or Franchise (https://business.nj.gov/pages/buy-an-existing-business ) - text at the top of the page doesn't respond correctly. At certain browser sizes the text overlaps with the page breadcrumbs 
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/114253061/193672826-19f944bf-1f36-48bb-858b-fef8cc5ee007.png">

2. Plan > Create a Business Plan (https://business.nj.gov/pages/create-a-business-plan) - Accordion responsiveness is buggy. Might not be high priority since we will be removing accordions in the upcoming sprints - 
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/114253061/193673752-4e819911-4fec-42a3-a679-13f6adb2bacc.png">

**Comment by carye3** [comment]
@dltinnovate can you implement this link styling (per USWDS) (eg external links): https://designsystem.digital.gov/components/link/

**Comment by amandabeall** [comment]
@dltinnovate Hey Joe, found another bug in B.NJ. Looks like something is wrong with the submit button on this page https://business.nj.gov/starter-kits/more-kits-comings-soon 

<img width="544" alt="Screen Shot 2022-10-05 at 4 09 38 PM" src="https://user-images.githubusercontent.com/114253061/194153810-60454a50-6baa-47d7-b1b7-11c6264fbe50.png">
