### ISSUE TITLE
Update "Required" Label for Tasks on the Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#3001]
As Poppy, I need a more streamlined "Required" label for Tasks on the Roadmap, so that I have a more visually appealing experience.

## Acceptance Criteria

**Desktop**
- Add Required text to the right of required tasks
- Bold task copy that is required.
- Remove Required Icon

**Mobile**
- Add Required text to the right of the status of the task

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12623%3A262580
- Mobile
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12638%3A263818

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux @carye3 @fiorella-io 
1) What happens when the task text wraps.. Would it look like the image below? The green box indicated the user is tabbing over the link.
2) The AC mentions bolded text, but the label in the design is not bolded. Which one should we use (content team can change it later if they choose to)

<img width="514" alt="Screen Shot 2022-06-10 at 1 48 22 PM" src="https://user-images.githubusercontent.com/72581979/173145380-1f69e8a8-7021-4d58-9517-485f908d4ce3.png">

**Comment by fiorella-io** [comment]
Hi @FarazA22 can we change the weight of "Required" to regular instead of bold? We need to bold the task name, not the "required" label. 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/91498500/173157301-200438bc-82aa-4bc0-97cf-15d9e321bc33.png">

**Comment by FarazA22** [comment]
@Jesslax 
Design is requesting the bold styling be removed from the required label. You can modify the label here.
Config -> taskDefaults -> requiredLabelText

**Comment by Jesslax** [comment]
@fiorella-io does this look right: 
![image](https://user-images.githubusercontent.com/78366346/173371127-1f48267b-15ad-446c-a2cc-57e9d4b70244.png)

**Comment by aaronvux** [comment]
@Jesslax spoke to Faraz.  He's going to try to make the change in the code.
