### ISSUE TITLE
Update Profile Box on Left Side of Oscar Dashboard

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#3015]
As  Oscar I need a more streamlined Profile section on the Dashboard so I'm not overwhelmed with content.

## Acceptance Criteria
- Display business name as Profile link, current date (Local NJ Date) on the right with ET designation
- Remove Profile link
- Remove Copy block

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Design

**Oscar**
- Desktop
https://www.figma.com/file/IKcrTIyvaS593LuJbAVFR3/Navigator-Designs-(Sprint-33%2B)?node-id=12556%3A262740

## Approvals
- [ ] UX Review
- [ ] PO Approval

**Comment by aloverso** [comment]
@aaronvux pre-grooming notes:
- I remember that last time we discussed this story, we were talking about the NJ local time. Two questions here:
  - can we clearly state why this is valuable when the user can easily access the date on their computer? Have we seen a need from users to be provided the current date?
  - what is the acceptance criteria around daylight savings? I see the designs show "EST" which implies we'll be switching the label between Daylight Savings Time and Standard Time? What is the value of tracking whether we're in daylight savings time, if we're only showing the date and not the time?
- have we user-tested the change to switch to linking the business name instead of a call-to-action like "Edit my profile"? Especially with accessibility for keyboard-only users who tab between interactable elements. Will they know where that will take them when they click that link?

**Comment by aaronvux** [comment]
@aaronvux I don't think we'll differentiate between daylight savings and standard time.  EST was to help the user understand it's East Coast time, but might not work if the user is trying to differentiate ET and EST.

@carye3 @fiorella-io can speak to the value asks

**Comment by carye3** [comment]
@aloverso everything here has gone through usability testing
- Date is used as reference for specific tasks, and is a universal pattern for dashboard products.
- Users still have two options for editing their profile: via the dropdown or here, so i don't think it poses an accessibility issue

**Comment by FarazA22** [comment]
<img width="804" alt="Screen Shot 2022-06-08 at 3 27 54 PM" src="https://user-images.githubusercontent.com/72581979/172700588-feaa01cd-af74-49e2-b493-905aea1fd58f.png">

**Comment by FarazA22** [comment]
@aaronvux the analytics spec we currently use for the dashboard is `"roadmap_profile_edit_button", "click", "go_to_profile_screen"`.  This is the same spec we are using for the roadmap page.

This spec is used for two different buttons on the dashboard page: 1) "edit my profile" button within the header and "updating your profile" link when calendar is not available.

Can you confirm if we are using the same spec for both links within the dashboard page?

**Comment by aaronvux** [comment]
@FarazA22 the profile link from the header dropdown should be account_menu_my_profile/click/go_to_profile_screen

**Comment by FarazA22** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
LGTM.  Please review @carye3 @fiorella-io
