### ISSUE TITLE
Content: Add child care industry 2

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#3815]

**Comment by Jesslax** [comment]
1) should they get the reseller task?
2) obtain a certificate of occupancy seems to be in the wrong location, should be somewhere in step 3?/replace the existing "Obtain Site Safety Permits" task? Or if you want it to replace the "evaluate your location" task, I think it needs different copy.
3) also home-based business q isn't being asked in the profile, which makes sense, but i am not seeing the place-based tasks, is that intentional
4) this formatting looks weird, we should ask for the ability to have subullets -for dev/content pairing while Im out
![image](https://user-images.githubusercontent.com/78366346/187751392-24607b3c-7289-443e-b3a4-6dae0ee5f2dc.png)
5) any task dependencies here?
6) change industry name to child care?

@CeciliaRam

**Comment by CeciliaRam** [comment]
@Jesslax feedback incorporated. Additional answers below:

1. Reseller task: If the Daycare provides food (snacks) for the kids they would be a reseller 
2. Certificate of Occupancy task: Moved to Step 3 and copy edited so it makes more sense
3. Place-based tasks: Not added intentionally because Daycare needs its own version
5. Added!
6.  Industry name change: We can totally change it back to Child Care Center
7.  Link to manual added

Also, for reference a list of the tasks for this roadmap: 
<img width="590" alt="Screen Shot 2022-09-13 at 1 54 54 PM" src="https://user-images.githubusercontent.com/86479586/189977290-e7f0cd67-08c6-45c9-a081-8bdb6abd8832.png">

**Comment by Jesslax** [comment]
Great thanks Ce! Should I review one more time, or ready to publish?

**Comment by CeciliaRam** [comment]
@Jesslax Roadmap is enabled but hasn't been pushed to dev yet. If you wanna take a look, it's still a good time :)
