### ISSUE TITLE
Content: research form numbers

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#4082]
Accounting
Acupuncture,
Architect,
Appraisal,
Autobody Repair,
Cosmetology (Individual, Shop),
Cannabis (Annual, Conditional, Conversion), Asked Toni-Anne
Certified Home Health Aid,
Commercial Driver's License,
Employment Agency,
Engineer,
Food Truck,
HVACR Contractor,
Real Estate Broker,
Liquor, @CeciliaRam research/ ask Don
Massage Therapist Business,
Mercantile, - @CeciliaRam research/ ask Don
School Bus, etc)
Get Authorization from Your Local Government: A license to operate in the municipalities where you applied - DO NOT DO
Search all licenses - DO NOT DO
Home Improvement Contractor

**Comment by CeciliaRam** [comment]
We can't move forward without being able to speak to someone for licenses that arent related to Consumer Affairs. 
Consumer Affairs did get back to us and gave us the info on the licenses they handle, though.

**Comment by CeciliaRam** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1IS2wkz8xblWtAMp9UNEPAR2JtA2nkkKDaz24BsQnBys/edit#gid=0

It's incomplete because we haven't heard back from everyone in the different agencies. We could use Consumer Affairs' license as Acceptance Criteria, though. When we make a new field in the profile/ task screen to save a license number, it should accept:
* At least 12 digits
*  A combination of letters and numbers

@Jesslax
