### ISSUE TITLE
Content: Cannabis Feedback

### ISSUE THREAD

**Issue by CeciliaRam** [newjersey/navigator.business.nj.gov#4418]

**Comment by CeciliaRam** [comment]
[ ] Conditional License: Move "determine site requirements" task to after conditional license
- Annual License: Move "determine site requirements" task to Step 3 but before Annual License
- Copy Iside "evaluate your location" task needs to add "check with local gov to make sure they have opted in to accept cannabis businesses. check local ordinances to make sure you can run a biz in your municipality" (but nicer)
- Both Roadmaps: remove business plan task
- NAICS: change recommendation to generic NAICS code (other)
- Bank account task: new cannabis bank account task. Add: “Any <spell out> FDIC insured bank cannot open an account for a Cannabis business” “Note: Private financing does not constitute as private bank account”
- Priority status task: Business Impact zone (line). Add: My business is in an impact zone that allows cannabis businesses
- Sign your lease task: make sign your lease task for cannabis. Add :"Make sure you understand the terms of this lease, have it legally reviewed" "Ask owner or landlord if it's <spell out acronym> FDIC backed mortgage because then they cant use that because this cannabis is not yet legal at the federal level"
- Research: Obtain zoning approvals: research to take out "get a resolution from your municipality" and make it its own task (draft)
- Research:  Standard Operating Procedures: list all 16 with brief 1 liner of what it is and who it is for (sellers? cultivators? who are these ppl). CTA? Learn more has this link: https://www.nj.gov/cannabis/documents/rules/NJAC%201730%20Personal%20Use%20Cannabis.pdf

**Comment by CeciliaRam** [comment]
Operating Procedures: 
There are lots and depend on the type of cannabis business. Here's a doc with a compilation of info:
https://docs.google.com/document/d/1GBynU_kaTZ8dWWzvWCWoAVqETV87Ku8rglLpk3pU6DM/edit#

**Comment by CeciliaRam** [comment]
@Jesslax this is ready for review

**Comment by Jesslax** [comment]
1) Evaluate Location task to something like "Identify a Community that Allows Cannabis Business" - I think that's the big takeaway for the task. And then maybe rename "General Site Considerations" to "Other Site Considerations"
2) Business bank account - wouldn't start a sentence with because. We should also update this section once we get the ability to create our own alert bars. Not sure how you'd like to track that, create a new tkt maybe?
3) Sign Your lease - would not start a sentence with because. Should it say "Other Contract Considerations" OR should we put some of the copy in the description section in the "Contract Considerations" seems like some of the cannabis things you note could go in that section.
4) We are discussing the zoning task on a separate thread. 
5) Make sure the dependencies are all included in here, I only see them on one task, not sure where else you want them.

Otherwise, looks good!
