### ISSUE TITLE
Content: NJBAC and NJEDA funding programs

### ISSUE THREAD

**Issue by kadamson-fearless** [newjersey/navigator.business.nj.gov#4657]
NJEDA Child Care Facilities Improvement Program
NJBAC Cannabis Training Academy

**Comment by kadamson-fearless** [comment]
NJBAC Cannabis Training Program
NJEDA Child Care Facilities Improvement Program

**Comment by kadamson-fearless** [comment]
Both programs are in review on netlify. Still waiting on a response from businessactioncenter@sos.nj.gov for the cannabis training program, but otherwise ready to review. 
@Jesslax

**Comment by Jesslax** [comment]
@kadamson-fearless for the  

For Cannabis program:
The phrase "Must be in the social equity, legacy, Impact Zone, diverse-owned, veteran, veteran-disabled, LGBTQ+ and/or microbusiness categories as defined on the [New Jersey Cannabis Businesses website]"  There are three specific names used by the cannabis industry to describe there, and we created contextual information for them - so we don't need to ask people to look elsewhere for definitions. Replace this with the proper name and related contextual information. You can find out what this is by  looking up the Cannabis roadmap then look at the priority status task -  there are three priority statuses and we define each of them with contextual information. No other feedback on this item

For the Child care facilities grant:
1. "Applicants must meet the following eligibility requirements:" because it's outside the stlyguide - isn't clear why you are making this statement - do you want to clarify that it is **ALL** applicants? where as the other ones are facility only applicants?
2. EIN should read Entity ID Number not entity ID, and should be linked to contextual information
3. NJDCF and DOL needs the acronym spelled out the first time
4. System for Award Management  needs a link
5. I made a new header to describe what elements of the project can be covered and included
a. Labor and materials cost for interior and exterior facility improvements to create high quality early childhood learning environments. See the full list of [[eligible facility improvement projects](https://www.njeda.com/wp-content/uploads/2022/05/Child-Care-Facilities-Improvement-Eligible-Projects.pdf)](https://www.njeda.com/wp-content/uploads/2022/05/Child-Care-Facilities-Improvement-Eligible-Projects.pdf)
b. Soft costs are capped at up to 20% of total grant and are limited to: architect fees, permit fees, construction management, freight and shipping delivery, environmental assessment - less of a benefit and more so details about what can be covered - maybe belongs in eligibility. 
7. "Total project costs between $50,000 and $200,000" the framing of the benefits isn't clear - reframed to say "Grant for $50,000 - $20,000" 
8. Can this be marked to publish?
