### ISSUE TITLE
Oscar Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#879]
As Oscar, I need the ability to create an account on the Navigator so I can access the Navigator functionality.

## Acceptance criteria

- Add new question for all users

**Step 1**
-- Have you already registered and formed your business? (Required)
- If Yes, advance to Oscar onboarding, If No, advance to Poppy onboarding

**Step 2**
- Do you know your Entity ID? (Optional)
-- Follow current validations for 10 digit number
-- Entity ID is not required
-- Contextual info: Learn more about your Entity ID. (follow existing description)
-- Display Entity ID field in Oscar Profile

**Step 3**
- What is your Business's Name (Required)
  - for business name error text, show inline helper text when it is missing, and if user tries to click next, show floating toast message. same behavior as Location dropdown right now
- Industry

**Step 4**
- Number of employees (separate story)
- Certifications (separate story)
- Location
- Home based business

## notes

- Upon completion of the onboarding steps, advance the user to the Poppy Roadmap.  (Design for Oscar Roadmap TDB)
- Include Feature Flag
- 508 Compliance
- Works in Mobile
- Follows Design

## Designs

Prototype:
https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?page-id=6025%3A108014&node-id=6029%3A110425&scaling=scale-down&starting-point-node-id=6029%3A110425

## Notes

- [ ] UX Review
- [ ] PO Review

**Comment by aaronvux** [comment]
Need story to integrate with Treasury using Entity ID to automatically populate existing business information.

**Comment by aaronvux** [comment]
@fiorella-io please attach the designs when they are ready.

**Comment by aaronvux** [comment]
Removed Industry identification from the AC. @fiorella-io Can you update the design please and let me know when it's ready so this story can be split by the team?

**Comment by kmelefsky** [comment]
@aloverso & @mikewolfd rather than splitting this story it may make sense to create tasks since there are only four steps now. Let us know if you think that won't work 
cc @aaronvux

**Comment by aloverso** [comment]
@kmelefsky @aaronvux Even with the consolidated steps, I'd prefer separate stories. My proposal for three stories instead:
1. add Have you already registered and formed your business? question, and if they select the Oscar path, show them the entity ID step, business name / location step, and advance them to roadmap
2. Add step 4 and add number-of-employees question
3. add certifications question

Part of my reasoning is that number-of-employees and certifications are both new fields, especially certifications which is a completely new _type_ of field (multiselect checkbox), and should be their own story worth of work

**Comment by aaronvux** [comment]
After speaking with Faraz, we need the user to specify their industry to display the home based business correctly.  Step 3 will now be: Business Name, Industry, Number of Employees.  Step 4 will be:  Location, Home-Based Business, and Certifications.  @fiorella-io can you please update the design?

**Comment by fiorella-io** [comment]
@aaronvux  The designs have been updated

**Comment by aloverso** [comment]
^ @Jesslax what do you think here?

**Comment by Jesslax** [comment]
Great question @FarazA22, I think option 2 is ideal. @aaronvux can we work together to address the need for more logic on the stories

**Comment by aaronvux** [comment]
Checked with Faraz, Option 2 will be implemented.  Nothing further needed at this time.

**Comment by aaronvux** [comment]
Not seeing the home-based business question.  Also, some formatting looks off in mobile.  See screenshot
<img width="360" alt="Screen Shot 2021-11-23 at 3 58 02 PM" src="https://user-images.githubusercontent.com/36163601/143059149-78d692eb-75fe-44f7-be1d-e136d7ed7abb.png">
.

**Comment by aaronvux** [comment]
@fiorella-io please review

**Comment by aloverso** [comment]
@aaronvux that's a good catch, but it looks like it's an existing bug in how we render contextual info all over the site. Mind if we open a new bug ticket for it so that it doesn't block this story? I'll start looking into it 

for example, on a task page:
![image](https://user-images.githubusercontent.com/6563663/143119514-f9eee356-b65d-4479-9554-c897130a512e.png)

**Comment by Jesslax** [comment]
@aaronvux  a few notes:

1) On the first screen we should add an option, and create a workflow for the user that may need to pick "I don't know" This is probably its own user story.

2) For the business name questions, should we do any kind of lookup? For example, we could look up to make sure that name is taken. If that name is not taken, it would suggest they wrote in the wrong business name. That said, if the only reason we are asking for the name is to make it the heading of this, we probably do not need to ask.

3a) Why do we need the industry question? @carye3, is the research showing we will need this question at all for Oscar?
3b) If we are going to keep the industry question, we should require an answer. Right now I can move to the next screen without answering this.

4) The onboarding headlines should have some type of design hierarchy? The "Tell Us About Your Business" and "Name" seem to be the same font size? @fiorella-io, can we add this to your Navigator Improvements list.

5) When the user inputs their EID in onboarding, the number should automatically display in their profile?

6) The user profile should clarify that they have either selected an established business or not, and the user should have the option to change that. We should write a story for this, does it need design?

7) Since we are not asking the Oscar user about their legal structure in onboarding, I think we should take it out of their profile. Later, when we are able to access Treasury data, that might look different.

**Comment by aaronvux** [comment]
> Spoke with @Jesslax 

1. We will add copy to address the "I don't know" people.
2. We'll keep an eye on this one with user feedback and metrics.
3. New story:  Require industry for Oscar.
4. @fiorella-io please look to see if we create a visual hierarchy
5. I believe this should already be happening
6. New Story:  Toggle between established business and prospective business
7.  New story/Oscar Dashboard story: Hide legal in Profile for Oscar.

**Comment by fiorella-io** [comment]
@aaronvux @Jesslax In the designs, they are different font size. "Tell Us About You Business" is 32px, and "Business Name" is 22px
![image](https://user-images.githubusercontent.com/91498500/143897026-37559f23-7616-431f-a81d-60aaecd937f6.png)

**Comment by aaronvux** [comment]
Updated AC to display Entity ID field in Oscar Profile.

**Comment by aloverso** [comment]
@aaronvux new change is ready

**Comment by Jesslax** [comment]
@aloverso I need the Oscar onboarding copy to be different from the Poppy onboarding copy on some of these screens. When I went to change the copy, they seemed like the same file. Please advise.

**Comment by aaronvux** [comment]
We will create a new story to separate the Oscar and Poppy onboarding content files.

**Comment by aaronvux** [comment]
Moving to staging :)
