### ISSUE TITLE
Add Number of Employees Field to Oscar Onboarding

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#947]
As Oscar, I need the ability to tell the Navigator the number of employees in my business so I can receive pertinent information relating to the size of my employee base.

## Acceptance criteria

**Step 4**
- Add Number of Employees Field to Step 4
- How many employees does your business have? (Required)
-- Input Field, numbers only
-- Limit to 7 digits

- Works in Mobile
- Follows Design
- 508 Compliant
- Include in Oscar Onboarding Feature Flag

## Design
Prototype:
https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?page-id=6025%3A108014&node-id=6029%3A110425&scaling=scale-down&starting-point-node-id=6029%3A110425

## Notes

- [x] UX Review
- [ ] PO Approval

**Comment by FarazA22** [comment]
@aaronvux Can you provide some clarification around the functionality of the dropdown. Is it a simple dropdown. In other areas we are allowing users to filter as they type a value into the drop down (auto-complete).

**Comment by aaronvux** [comment]
@Jesslax needs to confirm the range values.  @FarazA22 normal dropdown for now, no searching.

**Comment by aaronvux** [comment]
Updated the values so there is no overlap.  @Jesslax spoke with @FarazA22.  We need to think about the values and if it makes sense to be able to update them once this is live in production.  The issue is that once it is live, if we change the values, it will be really difficult to update the values in the database that users have already selected.  Also, there may also be an issue with if we give different roadmap steps based on the number of employees down the line.

**Comment by Jesslax** [comment]
@aaronvux I will get back to you Tuesday afternoon after I chat with Joe and Jaime.

**Comment by Jesslax** [comment]
@aaronvux @FarazA22 after much deliberation with Jaime and Joe, I think it will be better if the user can enter a # rather than a drop down. Is there a con to this from dev point of view?

Explanation: We are asking this question to see what funding programs users qualify for. However, different funding programs define "employee" differently--some ask for employees, some fte based on 40 hours a week, some fte based on 30 hours a week. Letting the user submit # of fte based on 35 hours a week will help us ensure we are getting them the most accurate programs. If later we notice a trend in how to group them, we can do that. But this will allow us to have more accurate information. Once we get Treasury info, they should have this #, and we wont need to ask the user anymore.

**Comment by aaronvux** [comment]
@FarazA22 @fiorella-io updated AC to input field and 7 digit number limit.

**Comment by FarazA22** [comment]
@Jesslax Thanks for sharing the additional context. I have a few more questions that I need answers to before wrapping up this story.

1) Based on the info provided above, this field captures the number of full-time employees an existing business owner has working under them. I want to confirm the number of part-time employees will be excluded. I'm asking because I need to define the correct aria label for screen readers and need clarification on whether it should read out 'Number of full time employees' or 'Number of employees' when the user navigates to the input field.

2) Your response mentioned funding programs can define an employee differently, do we want to capture 

Based on what you mentioned above, 
Since this question will be used to determine the funding programs a user is qualified for, are we specifically capturing the number of full time emplyees?

**Comment by fiorella-io** [comment]
The designs have been updated to the "Number of Employees" field

**Comment by Jesslax** [comment]
@FarazA22 great questions. Businesses can add up their part-time staff to ftes, so if they had 2 staff working 20 hours a week, they would add 1 employee. 
1. Part-time employees does not need to be a separate entry.
2. I will update the copy to explain how this work.
3. I can change the content myself right? If so, you don't need to worry about it.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
@FarazA22 I'm able to move forward using the next button without the number of employees field being populated and the field validation being active.

**Comment by FarazA22** [comment]
@aaronvux Made the fix to address the issue.

**Comment by aaronvux** [comment]
This looks good now.  @fiorella-io please review

**Comment by fiorella-io** [comment]
Looks good to me. Thanks, Faraz

**Comment by aaronvux** [comment]
Moving to staging.
